name: OpenItems
version: '1.0-SNAPSHOT'
main: su.nezushin.openitems.OpenItems
api-version: '1.21'
author: NezuShin
depend: [NBTAPI]
softdepend: [PlaceholderAPI]
commands:
  oedit: {}
  openitems:
    aliases: [oi, oitems]